# not available at Ubuntu 12.04 LTS:
#before_install:
#    - sudo apt-get update -qq
#    - sudo apt-get install -y pandoc pandoc-citeproc

# provided by https://github.com/mfenner/jekyll-travis/
# does not include pandoc-citeproc :-(
#install:
#    - export PATH="$HOME/pandoc:$PATH"
#    - mkdir $HOME/pandoc
#    - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
#    - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc -d $HOME/pandoc
#    - chmod +x $HOME/pandoc/pandoc
#    - pandoc --version

script: make
